### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED 

### ISSUE THREAD

**Issue by Bongnah** [sx-zhang/HOZ#9]
python main.py --title HOZ --model HOZ --workers 12 --gpu-ids 0
python full_eval.py --title HOZ --model HOZ --results-json HOZ.json --gpu-ids 0

When I ran the above two codes for training and evaluation, I got the following error. 

File "/home//miniconda3/envs/ng/lib/python3.6/site-packages/torch/nn/functional.py", line 1369, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

I wonder how to solve these issues

**Comment by Bongnah** [comment]
It looks like the error is caused by a mismatched dimension.

OSError: Unable to open file (unable to open file: name = './datasets/Scene_Data/FloorPlan211/depth.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
When I first ran the code with the dataset you provided, I got an error that the dataset didn't have a file. 
I checked the actual dataset you provided and found that the file is named det_feature_22_cates.hdf5, not depth.hdf5, so I fixed that part of the error.

However, when I tried to run it, I got a dimension error like that, so it seems that the dimension between the code and the dataset you provided is not correct. How can I solve this error?

**Comment by hqrss** [comment]
> It looks like the error is caused by a mismatched dimension.
> 
> OSError: Unable to open file (unable to open file: name = './datasets/Scene_Data/FloorPlan211/depth.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0) When I first ran the code with the dataset you provided, I got an error that the dataset didn't have a file. I checked the actual dataset you provided and found that the file is named det_feature_22_cates.hdf5, not depth.hdf5, so I fixed that part of the error.
> 
> However, when I tried to run it, I got a dimension error like that, so it seems that the dimension between the code and the dataset you provided is not correct. How can I solve this error?

您好，您的问题解决了没有，我也遇到了

**Comment by hqrss** [comment]
> It looks like the error is caused by a mismatched dimension.
> 
> OSError: Unable to open file (unable to open file: name = './datasets/Scene_Data/FloorPlan211/depth.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0) When I first ran the code with the dataset you provided, I got an error that the dataset didn't have a file. I checked the actual dataset you provided and found that the file is named det_feature_22_cates.hdf5, not depth.hdf5, so I fixed that part of the error.
> 
> However, when I tried to run it, I got a dimension error like that, so it seems that the dimension between the code and the dataset you provided is not correct. How can I solve this error?

Hello, has your problem been resolved? I have encountered the same issue.

**Comment by kylehuo8** [comment]
Encountered the same issue too.
